spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/framework?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    password: framework
    username: framework

vin:
  admin:
    controller:
      enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
